stages:
  - build
  - test
job1:
  stage: test
  script:
    - echo "I am job1"
    - echo "I am in test stage"
	- echo 'NewFile' > ./file
	- pwd
job2:
  stage: build
  script:
    - echo "I am job2"
    - echo "I am in build stage"
	- cat ./file
